/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qrcode.svg.example;

public class App {

    public static void main(String[] args) {
        try {
            // generate a PNG format QR Code file
            new PrintQR().write();
            // generate an SVG format QR Code file
            new PrintQRSVG().write();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}